//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentDefaultMeasurementType_Equipment = new HashSet<EquipmentDefaultMeasurementType_Equipment>();
            this.OperationEquipments = new HashSet<OperationEquipment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> EquipmentTypeID { get; set; }
        public Nullable<short> DependencyID { get; set; }
        public string Code { get; set; }
        public string Barcode { get; set; }
        public string Model { get; set; }
        public string ChassisNo { get; set; }
    
        public virtual DependencyEquipment DependencyEquipment { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDefaultMeasurementType_Equipment> EquipmentDefaultMeasurementType_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationEquipment> OperationEquipments { get; set; }
    }
}
