//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempPurchaseOrder()
        {
            this.TempPurchaseOrderItems = new HashSet<TempPurchaseOrderItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<short> OrderStatusID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<short> ProcurementOfficialsID { get; set; }
        public string Description { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ProcurementOfficial ProcurementOfficial { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempPurchaseOrderItem> TempPurchaseOrderItems { get; set; }
    }
}
