//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualProductivity
    {
        public int ID { get; set; }
        public Nullable<int> OperationEquipmentID { get; set; }
        public string Measurement { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalUnitProductivity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ForfeitAmount { get; set; }
        public string DesciptionForfeitAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.TimeSpan> TransactionTime { get; set; }
        public string Description { get; set; }
    
        public virtual OperationEquipment OperationEquipment { get; set; }
    }
}
