//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office_Career
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office_Career()
        {
            this.Office_Employee = new HashSet<Office_Employee>();
        }
    
        public short ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> CareerTypeID { get; set; }
        public Nullable<bool> isSysUser { get; set; }
        public Nullable<bool> isSysAdmin { get; set; }
        public string Description { get; set; }
    
        public virtual Office_CareerType Office_CareerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office_Employee> Office_Employee { get; set; }
    }
}
