//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationEmployeeCareer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationEmployeeCareer()
        {
            this.OperationRepositoryDatas = new HashSet<OperationRepositoryData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GeneralDataID { get; set; }
        public Nullable<short> Employee { get; set; }
        public Nullable<short> Career { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual OperationCareer OperationCareer { get; set; }
        public virtual OperationEmployee OperationEmployee { get; set; }
        public virtual OperationGeneralData OperationGeneralData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationRepositoryData> OperationRepositoryDatas { get; set; }
    }
}
