//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationProductivity
    {
        public int ID { get; set; }
        public Nullable<int> OperationGeneralDataID { get; set; }
        public Nullable<short> ProductivityTypeID { get; set; }
        public string EngineeringAssessment1 { get; set; }
        public string EngineeringAssessment2 { get; set; }
        public string EngineeringAssessment3 { get; set; }
        public string EngineeringAssessment4 { get; set; }
        public string Description { get; set; }
    
        public virtual OperationGeneralData OperationGeneralData { get; set; }
        public virtual ProductivityType ProductivityType { get; set; }
    }
}
