//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamerQasaly.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPurchaseOrderItem
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public decimal Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TempPurchaseOrder TempPurchaseOrder { get; set; }
    }
}
